// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgCH1lFcoCnBNeZwaPNm2ioaJxgJ-jBnc',
    appId: '1:616653315133:web:edcae9be2e98c5a5145e54',
    messagingSenderId: '616653315133',
    projectId: 'flutter-learn-ebe80',
    authDomain: 'flutter-learn-ebe80.firebaseapp.com',
    storageBucket: 'flutter-learn-ebe80.appspot.com',
    measurementId: 'G-1RVQKWJ1YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxkVB6NGXex5oRP93ZtJFlnBFNuz8IJ-4',
    appId: '1:616653315133:android:2081669e7f0de77f145e54',
    messagingSenderId: '616653315133',
    projectId: 'flutter-learn-ebe80',
    storageBucket: 'flutter-learn-ebe80.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgCH1lFcoCnBNeZwaPNm2ioaJxgJ-jBnc',
    appId: '1:616653315133:web:0d1fa62c804892a6145e54',
    messagingSenderId: '616653315133',
    projectId: 'flutter-learn-ebe80',
    authDomain: 'flutter-learn-ebe80.firebaseapp.com',
    storageBucket: 'flutter-learn-ebe80.appspot.com',
    measurementId: 'G-MGXYKG2EL4',
  );
}
